version: "3.8"

services:
  accounting:
    image: "accounting-local:latest"
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DATA_BASE_PASSWORD_TYPE=iam
      - FLYWAY_ENABLED=false
    profiles:
      - local-server
  postgres:
    image: "postgres:14"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
